INSERT INTO page VALUES (0);
INSERT INTO page VALUES (1);
INSERT INTO page VALUES (2);
INSERT INTO page VALUES (3);

INSERT INTO link VALUES (0, 1);
INSERT INTO link VALUES (0, 2);
INSERT INTO link VALUES (0, 3);
INSERT INTO link VALUES (1, 0);
INSERT INTO link VALUES (1, 3);
INSERT INTO link VALUES (2, 2);
INSERT INTO link VALUES (3, 1);
INSERT INTO link VALUES (3, 2);

